### ISSUE TITLE
Adding unecessary quotes updating .travis.yml

### ISSUE THREAD

**Issue by SBoudrias** [iamstarkov/generator-travis#10]
`.travis.yml` before

``` yml
before_script:
  - export NODE_PATH="$NVM_PATH/../node_modules"
```

And after

``` yml
before_script:
  - 'export NODE_PATH="$NVM_PATH/../node_modules"'
```

Is there a way to keep the style cleaner?

**Comment by iamstarkov** [comment]
i will take a look

**Comment by iamstarkov** [comment]
can you take a look as well, im afraid i dont have time. i will happy to merge this fix

**Comment by iamstarkov** [comment]
btw, wanna be a co-maintainer?

**Comment by SBoudrias** [comment]
@iamstarkov always happy to help :)

**Comment by iamstarkov** [comment]
@SBoudrias added you as a collaborator

**Comment by iamstarkov** [comment]
@SBoudrias what do you think about moving this repo into yeoman org?

**Comment by SBoudrias** [comment]
@iamstarkov we could, but I'm happy to have it here too. Whatever you prefer :)

**Comment by Myhlamaeus** [comment]
It seems that using [js-yaml](https://www.npmjs.com/package/js-yaml) instead of [yamljs](https://www.npmjs.com/package/yamljs) would fix it (at least for this specific case).
