### ISSUE TITLE
Ordering/Cleaning versions

### ISSUE THREAD

**Issue by SBoudrias** [iamstarkov/generator-travis#11]
The generator adds new versions without considering style and ordering of the `node_js` section. So that's a request in two parts:
1. I'd like if the generator could sort the versions (more recent to oldest would be my preference)
2. If the style could stay consistent (strings `'0.10'` or versions markers `v4`. My pref is always go `v0.10`, etc)

**Comment by eddiemonge** [comment]
I'd say drop the <4 versions and then everything is nice

**Comment by iamstarkov** [comment]
@eddiemonge 0.10 and 0.12 are LTS versions, so a lot of people will stil use your code in enterprise production on nodejs 0.10, thats why they are in the list. And as far as Travis testing is free, then its easy to know, if your software will work under LTS versions or not, if not you have a choice: either fix bugs or just remove unsupported versions.

**Comment by SBoudrias** [comment]
Yup, I agree LTS support should be kept by default.

**Comment by eddiemonge** [comment]
They aren't according to the official docs: https://nodejs.org/en/download/releases/

By having to support these, it means we can't do fun es2015 things without additional steps/flags/etc

**Comment by iamstarkov** [comment]
0.10 and 0.12 are definitely in the [LTS list](https://github.com/nodejs/LTS/)
